### ISSUE TITLE
"Timing out" is logged

### ISSUE THREAD

**Issue by Ronnyrr** [Pomax/Font.js#23]
Hi, I tried using your plugin. I'm loading several fonts by doing the following on document ready:

```
preloadFonts([
        '/path/fonts/Font.otf'
        '/path/fonts/Font2.otf'
]);

function preloadFonts(arrayOfFonts)
{
    $(arrayOfFonts).each( function(i, src) {
        var loadFont = new Font();
        loadFont.src = src;
        loadFont.onload = function () {
            console.log('Font "'+ src +'" loaded');
        }
    });
}
```

I'll get the console.log that the font is loaded, but I'm also getting a log "Timing out", which (correct me if I'm wrong) means that the font isn't loaded correctly. And when I start to display something where the font is used I first see a standard webfont for a few seconds.

Any idea what I can do about it? Thanks!

**Comment by Wildhoney** [comment]
@Pomax I also got a similar issue, and so I was doing a bit of debugging. It seems that the `printChar` it uses for testing the font is an empty string (`""`).

On [line 425](https://github.com/Pomax/Font.js/blob/master/Font.js#L425):

```javascript
printChar = String.fromCharCode(endChar);
```

Where `endChar` is `129` for the [following Optima TTF font](https://www.dropbox.com/s/9v1scvq1263s3b4/optima.ttf?dl=0).

I assume the fix in this instance is to detect if the yielded `printChar` is empty, and if so, to revert to the `printChar` default of `A`. However, before simply opening a PR for this scenario, I thought I'd post it as an issue, because there's no doubt that you know more than me about fonts :+1:

**Comment by Pomax** [comment]
@Wildhoney interesting find, can you file that as a new issue instead please?

**Comment by Vadimus** [comment]
Got similar issue. Just added condition `chr > 32` to `printable`
