### ISSUE TITLE
Multiple files loaded in chome

### ISSUE THREAD

**Issue by antag0n1st** [Pomax/Font.js#35]
Just noticed , that the same font file is loaded 3 times

**Comment by Pomax** [comment]
This project is effectively no longer under active maintenance, since there are better alternatives available these days (OpenType.js, Fontkit, etc), so unless this is a thing that you really need fixed, and you're willing to take a stab at patching the code to do the right thing, this issue will probably not get fixed.

**Comment by cyberwombat** [comment]
Unfortunately this project appears to be the only one that does what it does.OpenType cannot load fonts for the browser to use (i.e. @font-face) and TypeKit afaik has no support for measuring text.

**Comment by Pomax** [comment]
you may want to check out https://github.com/typekit/webfontloader

**Comment by Pomax** [comment]
obsolete with the 2019 rewrite
