### ISSUE TITLE
font rejected by sanitizer in mozilla

### ISSUE THREAD

**Issue by antag0n1st** [Pomax/Font.js#36]
but the issue can be solved by adding quotation marks at:

format('eot')

**Comment by Pomax** [comment]
actually, EOT's effectively deprecated now that Microsoft's officially stopped supporting anything that isn't the latest version of IE on still-supported versions of windows, so for practical purposes that means the IE target is v11, which means the IE fix with `eot` format should just be taken out.

That said, as per the README.md this project is essentially no longer maintained, having been surpassed by things like OpenType.js and Fontkit, so I'm not sure there's much value in fixing this anymore, unless you have a use-case in which it's still worth using this library instead of a more recent one.

**Comment by Pomax** [comment]
obsolete with the 2019 rewrite
