### ISSUE TITLE
Upload font

### ISSUE THREAD

**Issue by RoelN** [Pomax/Font.js#64]
What would be the preferred way to "upload" a font through drag/drop or a file input?

I saw [this issue](https://github.com/Pomax/Font.js/issues/30), which implies there is a mechanism in the new Font.js. But passing a base64 file trips up the filetype recognition.

Is there a cleaner way?

(Also, would file/font type detection be more thorough, e.g. by ignoring extension and checking on byte level?)

**Comment by Pomax** [comment]
You shouldn't be creating base64 data, `Font` operates on the plain data. If the problem is the `getFontCSSFormat` function not having that information available because the URL we should update that function to understand [blobs](https://developer.mozilla.org/en-US/docs/Web/API/Blob/Blob), which can be created with the mime-type already set.

**Comment by Pomax** [comment]
we added this =D
