### ISSUE TITLE
getSupportedCharCodes returns 0xFFFF as supported char

### ISSUE THREAD

**Issue by RoelN** [Pomax/Font.js#68]
As the last `start`/`end` combination, [getSupportedCharCodes](https://github.com/Pomax/Font.js/blob/26e3ba21b59e6b6d3a1f7072120faf5e19299739/src/opentype/tables/simple/cmap.js#L31) returns `{start: 65535, end: 65535}`. This appears to be the Unicode character for "not a Unicode character".

The fonts tested do not have a character defined at `0xffff`.

**Comment by Pomax** [comment]
Good catch, all segment-based subtable formats should be checking to verify the segment doesn't simply mean "end of segments, nothing here".

**Comment by Pomax** [comment]
I feel like we solved this previously, can you test to see if this is still the case @RoelN ?

**Comment by RoelN** [comment]
Just tested, but `0xffff` is still reported as a character, so at Wakamai Fondue we still need to [account for that](https://github.com/Wakamai-Fondue/wakamai-fondue-engine/blob/master/src/fondue/Fondue.js#L379).

**Comment by Pomax** [comment]
if  you have a reproducible case for it, I can add that as a test - does this happen on any of the Source Code or Open Sans fonts?

**Comment by Pomax** [comment]
fixed in https://github.com/Pomax/Font.js/commit/495ec044a6aa35d23961c136adad61e316a59929, specifically, by testing for surrogate and noncharacter codes: https://github.com/Pomax/Font.js/commit/495ec044a6aa35d23961c136adad61e316a59929#diff-1496abdd1291c189b17f8168f8363662ad0df7697af702539e98e3a1a3023178R91-R103
