### ISSUE TITLE
Name table entries contain null bytes

### ISSUE THREAD

**Issue by RoelN** [Pomax/Font.js#74]
If my text is "Wakamai Fondue rules!", `font.opentype.tables.name.get(19)` will return:

```
\x00W\x00a\x00k\x00a\x00m\x00a\x00i\x00 \x00F\x00o\x00n\x00d\x00u\x00e\x00 \x00r\x00u\x00l\x00e\x00s\x00!
```

I could filter them out [here](https://github.com/Pomax/Font.js/blob/master/src/opentype/tables/simple/name.js#L40) but I guess there is a neater solution, probably involving getting the data at the right amount of bits?

**Comment by khaledhosny** [comment]
You are getting UTF-16 strings.

**Comment by Pomax** [comment]
this feels like it's because of the mac/microsoft string difference... we'd need to check which format the name record uses, and compensate for the two-byte string format that either the mac or windows platforms use. I forget which of the two was short and which was long off hand, but that should be something we can solve on the line you highlighted, by consoluting the record's platform/encoding

**Comment by Pomax** [comment]
Do you have a test font we can use to debug this one?

**Comment by khaledhosny** [comment]
Windows platform name strings are UTF-16, aren’t they?

**Comment by Pomax** [comment]
I couldn't remember which of the two was an 8 bit ansi-like and which was utf16, but yes.

**Comment by Pomax** [comment]
landed in https://github.com/Pomax/Font.js/blob/master/src/opentype/tables/simple/name.js#L51-L92 as unicode parsing for platforms 0 and 3, and "ascii" byte parsing for everything else. That's certainly not perfect, but I'll be filing a followup issue around line 91:

> // TODO: if someone wants to finesse this/implement all the other string encodings, have at it!

**Comment by Pomax** [comment]
https://github.com/Pomax/Font.js/issues/85
